hygraph/rich-text

.changeset/chilled-bears-drum.md
packages/react/src/RenderText.tsx
packages/react/test/RichText.test.tsx
packages/react/test/__snapshots__/RichText.test.tsx.snap

This PR fixes an issue that was preventing empty space from being rendered.

fix(react): empty space not rendered

---

.changeset/long-dancers-reply.md
.changeset/rare-ligers-appear.md
package.json
packages/react/README.md
packages/react/src/RichText.tsx
packages/react/src/defaultElements.tsx
packages/react/test/RichText.test.tsx
packages/react/test/content.ts
packages/types/src/index.ts

This PR adds support for removing specified elements if they would be rendered empty
Maybe the naming of the property determining whether an empty element should be rendered or not could be changed, it's not as descriptive as it could be. (I did not find another name though)

feat(react): remove empty elements from rendering

---

packages/react-renderer/README.md

`children` is not a valid prop

docs(react-renderer): rename children to content

---

.changeset/eight-balloons-design.md
packages/react-renderer/src/defaultElements.tsx
packages/react-renderer/test/RichText.test.tsx
packages/react-renderer/test/content.ts
packages/types/src/index.ts

Related to [#5](https://github.com/GraphCMS/rich-text/issues/5#issuecomment-874637306).
To reproduce the bug:
- Add a table
- Insert a row
- Insert a column
- Render it, and you'll see the `validateDOMNesting` error (also, on the HTML, you'll find an empty `<thead></thead>`.
Closes MAR-1910.

fix(react): empty thead being renderered

---

.changeset/wild-frogs-sort.md
packages/react-renderer/README.md

Unfortunately, I couldn't figure out an implementation for `gatsby-plugin-image`. I've tried using the `StaticImage`, but it didn't work as expected. The `GatsbyImage` component (for dynamic images) needs the image data fetched from a query. There's no way to fetch from a query right now (at least I don't know, maybe @notrab could help here).
Closes MAR-1897 and MAR-1898

docs(react): add examples for next image and gatsby link

---

.changeset/tasty-seas-reply.md
packages/html-to-slate-ast/src/index.ts

The issue:
A user pasted a document into a Rich Text field, and the copy-pasted data contained an image that had not been uploaded via GraphCMS's Asset flow.
A copy-pasted image is currently transformed into the following AST:
```
{
"href": "<href>",
"type": "link",
"children": [
{
"href": "<href>.png",
"type": "link",
"title": "<title>",
"children": [], <- the issue
"openInNewTab": true
}
]
}
```
The correct shape of a link would have a text node in `children`. We need to set that node to the `src` value of an image:
```
{
"href": "<href>",
"type": "link",
"children": [
{
"href": "<href>.png",
"type": "link",
"title": "<title>",
"children": [{ text: "<href>.png" }],
"openInNewTab": true
}
]
}
```
A reproduction with and without any text children nodes in a link: …

Fix AST shape of a parsed copy-pasted image

---

.changeset/giant-bottles-whisper.md
packages/html-to-slate-ast/package.json
packages/html-to-slate-ast/src/index.ts
packages/html-to-slate-ast/test/image.html
packages/html-to-slate-ast/test/index.test.ts
yarn.lock

https://user-images.githubusercontent.com/34208415/128988710-cdb7763b-40b7-40f7-abf7-a623f77b11b9.mp4
Resolves ENG-3787

Fix text node when pasting images; sanitize URLs

---

.changeset/angry-moons-share.md
.changeset/shy-news-confess.md
examples/react/content.ts
examples/react/index.tsx
examples/react/package.json
package.json
packages/react-renderer/README.md
packages/react-renderer/src/defaultElements.tsx
packages/react-renderer/test/RichText.test.tsx
packages/types/src/index.ts

This PR adds support for rendering code blocks.
Closes MAR-2137

feat(react): add support for rendering code blocks

---

.changeset/wicked-eyes-run.md
packages/html-to-slate-ast/examples/node-script.js
packages/html-to-slate-ast/package.json
packages/html-to-slate-ast/src/index.ts
packages/html-to-slate-ast/test/index.test.ts

Fix links with marks, inline comments, lists

---

.changeset/strange-paws-sing.md
packages/html-to-slate-ast/src/index.ts
packages/html-to-slate-ast/test/index.test.ts
packages/react-renderer/src/RichText.tsx
packages/react-renderer/src/defaultElements.tsx
packages/react-renderer/test/content.ts

If a `li` node has a nested list among its children, wrap each child in an `list-item-child` node.
This corresponds to the changes we are about to introduce in the webapp.

Update nested lists handling

---

.changeset/little-colts-learn.md
.changeset/spotty-dogs-wonder.md
packages/react-renderer/test/RichText.test.tsx
packages/types/src/index.ts

Updates `EmbedProps` type and adds a test for custom rendering of an inline embed.

Introduce inline embeds

---

packages/react-renderer/README.md

I was [asked on Slack](https://graphcms.slack.com/archives/C9ERN8GFK/p1638801510191400?thread_ts=1638619040.179500&cid=C9ERN8GFK) to provide my example for generating low-quality image placeholders (LQIP) using Next.js and [Plaiceholder](https://github.com/joe-bell/plaiceholder).
To lower the barrier of entry for newcomers, I wanted to show a complete setup. If needed, the example can be shortened.

docs(react): add example for Next.js with placeholder images

---

packages/react-renderer/src/RichText.tsx
packages/react-renderer/test/RichText.test.tsx
packages/react-renderer/test/content.ts

Hi,
I noticed that currently working with nested inline embeds the references are not correctly passed along (see https://github.com/GraphCMS/rich-text/blob/main/packages/react-renderer/src/RichText.tsx#L184)
This PR passes the references, I also added a test to ensure there are no regressions in the future

fix: pass reference for nested embeds

---

.changeset/sweet-bananas-punch.md
packages/html-to-slate-ast/test/index.test.ts
packages/react-renderer/src/RenderText.tsx
packages/react-renderer/src/RichText.tsx
packages/react-renderer/test/RichText.test.tsx
packages/react-renderer/test/__snapshots__/RichText.test.tsx.snap

This PR fixes an issue where `\n` wasn't converted to `<br />`.
Important notes: 
- The `&NoBreak;` entity will still show up, but it's not relevant.
- If the parent node is a code block, the text won't be serialized, as it can break the content.

fix(react): \n not converted to <br />

---

packages/html-to-slate-ast/README.md
packages/html-to-slate-ast/examples/graphql-request-script.js

This PR aims to add an example for usage of the `html-to-slate-ast` using graphql-request. 
Since the output from the `htmlToSlateAST` function is not an RichText object, directly passing this output for the `content` in the currently given documentation example field will not work, so that's why I thought this example would be a good idea.

docs: add html-to-slate-ast client example

---

.changeset/cool-books-relax.md
packages/react-renderer/src/RenderText.tsx

Changes the key from `line` to `index`. Since `line` will be empty all the time, using the `index` is the best alternative here.
This fixes the same keys warning from React.
Closes #70

chore: use index as key on line break

---

.changeset/sour-gifts-glow.md
packages/html-to-slate-ast/src/index.ts
packages/html-to-slate-ast/test/index.test.ts

Allows parsing GCMS block, inline embeds into valid nodes.

chore: parse GCMS embeds into valid nodes

---

.changeset/pretty-fans-hug.md
packages/html-renderer/package.json
packages/react-renderer/package.json
yarn.lock

This PR fixes an issue when rendering an element that depends on the `escape-html` package, which was not installed on the `html-renderer` package.
```
error - ./node_modules/@graphcms/rich-text-html-renderer/dist/rich-text-html-renderer.esm.js:2:0
Module not found: Can’t resolve ‘escape-html’
Import trace for requested module:
./pages/form-sidebar.tsx
```

chore(deps): add escape-html

---

.changeset/giant-lamps-develop.md
.changeset/serious-masks-compete.md
packages/html-renderer/README.md
packages/html-renderer/src/defaultElements.tsx
packages/html-renderer/src/elements/Image.tsx
packages/html-renderer/src/elements/Link.tsx
packages/html-renderer/src/elements/Video.tsx
packages/html-renderer/src/index.ts
packages/html-renderer/src/types.ts
packages/html-renderer/test/__snapshots__/index.test.ts.snap
packages/html-renderer/test/index.test.ts
packages/react-renderer/README.md
packages/react-renderer/src/RichText.tsx
packages/react-renderer/src/defaultElements.tsx
packages/react-renderer/src/types.ts
packages/react-renderer/test/RichText.test.tsx
packages/react-renderer/test/__snapshots__/RichText.test.tsx.snap
packages/types/src/index.ts

This PR adds support for Link Embeds for both packages, React and HTML. The documentation and tests for the new feature were also added.

feat: add support for link embeds

---

.changeset/serious-hotels-love.md
examples/content-example.ts
packages/html-renderer/test/index.test.ts
packages/react-renderer/src/elements/Image.tsx
packages/react-renderer/test/RichText.test.tsx

This fix is related to an issue that usually happens with SVG. When an SVG is saved, GraphCMS can't set its dimensions, so the width and height of the SVG file are set to 0. So when rendering it, the image will be hidden because the width/height is set to 0. This PR makes sure we only add the width and height attributes if they are bigger than 0. Since the SVG usually has a width and height defined in its document, it will be rendered using its size.

fix: don't include width and height if set to 0

---

.changeset/two-lions-guess.md
examples/content-example.ts
packages/html-renderer/README.md
packages/html-renderer/src/index.ts

Export elements functions to be able to reuse them on customs renders

feat: export elements functions

---

.changeset/eight-elephants-battle.md
packages/html-to-slate-ast/package.json
yarn.lock

If tests are passing, we should be good to go. There are no breaking changes apart from the vulnerability issue fixed on @braintree/sanitize-url 6.0.0.

chore: update @braintree/sanitize-url to latest version

---

.changeset/ten-carpets-search.md
.github/workflows/main.yml
packages/html-to-slate-ast/README.md
packages/html-to-slate-ast/examples/node-script.js
packages/html-to-slate-ast/package.json
packages/html-to-slate-ast/tsup.config.ts
yarn.lock

Our library uses `jsdom` for DOM operations in Node.js environments. During the bundling process with tsup/esbuild, the module `xhr-sync-worker.js` from `jsdom` was not being correctly resolved, leading to a runtime error.
We have set `skipNodeModulesBundle` to `true` in our tsup configuration. This change instructs tsup/esbuild not to bundle the `node_modules` dependencies. As a result, Node.js handles the resolution and loading of modules at runtime, including the complex loading mechanisms used by `jsdom`.
This fix requires `jsdom` (and any other external module we use) to be installed in the user's project (we already recommend this), as our library now depends on these modules being present at runtime. This approach ensures that all dynamically loaded resources and complex module …

fix: missing `xhr-sync-worker.js` in `jsdom`
